version: '3.7'
services:
  nebula-stats-exporter:
    image: centos:7
    command:
      - ./nebula-stats-exporter
      - --bare-metal
      - --bare-metal-config=/config.yaml
      - --listen-address=:9200
    ports:
      - 9200:9200
    volumes:
      - ./vendors/nebula-stats-exporter/nebula-stats-exporter:/nebula-stats-exporter
      - ./vendors/nebula-stats-exporter/config.yaml:/config.yaml
    networks:
      - nebula-net

  prometheus:
    image: centos:7
    volumes:
      - ./vendors/prometheus/prometheus:/prometheus
      - ./vendors/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/data/prometheus:rw
    environment:
      USER: root
    command:
      - ./prometheus
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - nebula-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nebula-http-gateway:
    image: centos:7
    environment:
      USER: root
    volumes:
      - ./vendors/nebula-http-gateway/nebula-httpd:/nebula-httpd
      - ./vendors/nebula-http-gateway/conf:/conf
      - ./vendors/nebula-http-gateway/logs:/logs
      - ./uploads:/upload-dir:rw
    ports:
      - 8090:8090
    command:
      - ./nebula-httpd
    networks:
      - nebula-net
  nebula-dashboard:
    image: centos:7
    ports:
      - 7003:7003
    volumes:
      - ./config.json:/config.json
      - ./dashboard:/dashboard
      - ./public:/public
    command:
      - ./dashboard
    environment:
      USER: root
    networks:
      - nebula-net

networks:
  nebula-net:
    external: true

